### ISSUE TITLE
How should I put the location of dataset?

### ISSUE THREAD

**Issue by Jamie-Cheung** [NVlabs/denoising-diffusion-gan#15]
(th1.71) zzj@zzj:~/disk1/zzj/denoising-diffusion-gan-main$ python train_ddgan.py --dataset lsun
starting in debug mode
Traceback (most recent call last):
  File "train_ddgan.py", line 600, in <module>
    init_processes(0, size, train, args)
  File "train_ddgan.py", line 470, in init_processes
    fn(rank, gpu, args)
  File "train_ddgan.py", line 226, in train
    train_data = LSUN(root='/datasets/LSUN/', classes=['church_outdoor_train'], transform=train_transform)
  File "/home/zzj/disk1/zzj/denoising-diffusion-gan-main/datasets_prep/lsun.py", line 95, in __init__
    transform=transform))
  File "/home/zzj/disk1/zzj/denoising-diffusion-gan-main/datasets_prep/lsun.py", line 33, in __init__
    readahead=False, meminit=False)
lmdb.Error: /datasets/LSUN//church_outdoor_train_lmdb: No such file or directory

![image](https://user-images.githubusercontent.com/100945715/183428299-b3864040-d9ef-4360-9b62-15916689fec2.png)

**Comment by KomputerMaster64** [comment]
I am facing similar issue. How did you resolve it.. I have main dataset directory `datasets` which contains directory `ffhq-lmdb` which then contrains the `train.lmdb` and `validation.lmdb` directories.
![image](https://user-images.githubusercontent.com/68422504/191057578-8242fc8a-4481-4907-a9eb-2498f43009c4.png)

**Comment by ChauvinisticJonatha** [comment]
> I am facing similar issue. How did you resolve it.. I have main dataset directory `datasets` which contains directory `ffhq-lmdb` which then contrains the `train.lmdb` and `validation.lmdb` directories. ![image](https://user-images.githubusercontent.com/68422504/191057578-8242fc8a-4481-4907-a9eb-2498f43009c4.png)

Sorry, I haven't solved it.
